plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  "@testing-library/vue@*":
    dependencies:
      "pretty-format": "^29.3.1"
  "@vue/compiler-core@*":
    dependencies:
      "@babel/types": "^7.20.7"
