name: Update database types

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn update-types
    - name: Check for file changes
      id: git_status
      run: |
        echo "::set-output name=status::$(git status -s)"
    - name: Commit files
      if: ${{contains(steps.git_status.outputs.status, ' ')}}
      run: |
        git add src/db.types.ts
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "chore(supabase): update database types" -a
    - name: Push changes
      if: ${{contains(steps.git_status.outputs.status, ' ')}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: ${{ github.ref }}

